version: "3.6"
services:
  hbase-master1:
    image: porker/ubuntu:18.04 # 镜像的名字
    container_name: hbase-master1 # 容器名字
    working_dir: /hbase
    environment: # 环境变量
      JAVA_HOME: /java
      HBASW_HOMW: /hbase
      ZOOKEEPER_HOME: /zookeeper
    ports: # 映射端口到主机上
    - "2181:2181"
    - "16010:16010"
    - "16020:16020"
    - "16030:16030"
    volumes:
    - "./hbase-2.2.2:/hbase" # hbase 目录映射
    - "../docker-java-home:/java" # jdk 目录映射 冒号左边路径为宿主机上的路径，右边为容器内的路径，若需要修改jdk，则修改左边路径即可
    entrypoint: 
    - /usr/sbin/sshd
    - -D