version: "3.6"
services:
  hadoop-master1:
    image: porker/ubuntu:18.04 # 镜像的名字
    container_name: hadoop-master1 # 容器名字
    working_dir: /hadoop
    environment: # 环境变量
      JAVA_HOME: /java
      HADOOP_HOME: /hadoop
      HADOOP_CONFIG_HOME: /hadoop/etc/hadoop
    ports: # 映射端口到主机上
    - "9870:9870"
    - "8088:8088"
    - "19888:19888"
    - "9000:9000"
    - "10020:10020"      
    networks: # docker 网络设置
      hadoop:
        aliases:
        - hadoop-master1
    volumes: 
    - "./hadoop-3.2.1:/hadoop" # hadoop 目录映射
    - "../docker-java-home:/java" # jdk 目录映射 冒号左边路径为宿主机上的路径，右边为容器内的路径，若需要修改jdk，则修改左边路径即可
    entrypoint: 
    - /bin/bash
    - start.sh
  hadoop-slave1:
    image: porker/ubuntu:18.04
    container_name: hadoop-slave1
    working_dir: /hadoop
    environment:
      JAVA_HOME: /java
      HADOOP_HOME: /hadoop
      HADOOP_CONFIG_HOME: /hadoop/etc/hadoop
    networks:
      hadoop:
        aliases:
        - hadoop-slave1
    volumes: 
    - "./hadoop-3.2.1:/hadoop"
    - "../docker-java-home:/java"
    entrypoint: 
    - /bin/bash
    - start.sh
  hadoop-slave2:
    image: porker/ubuntu:18.04
    container_name: hadoop-slave2
    working_dir: /hadoop
    environment:
      JAVA_HOME: /java
      HADOOP_HOME: /hadoop
      HADOOP_CONFIG_HOME: /hadoop/etc/hadoop
    networks:
      hadoop:
        aliases:
        - hadoop-slave2
    volumes: 
    - "./hadoop-3.2.1:/hadoop"
    - "../docker-java-home:/java"
    entrypoint: 
    - /bin/bash
    - start.sh
networks:
  hadoop:
    driver: bridge